# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 087656ec022944aef1d382f1281ef29d47f651afd4e163aebec0f04b92f1777f989c139defc66ea733984812d1e738946da9e624f7f3976166050b56ac63c29d

test:
  secret_key_base: 10b009269cfb1313e42ea9e9e52808417eb0986c2650d42dd1d21c10c63978324cc57bb450d1d7ab86b36dee020064a5cddca69605e694852c551042fdf9c374

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
